### ISSUE TITLE
Raapijat hiekkalaatikossa?

### ISSUE THREAD

**Issue by pe3** [kansanmuisti/datavaalit#1]
Kiinnostaa ihan yleisesti ajetaanko raapijat jotenkin rajoitetuilla oikeuksilla?

**Comment by juyrjola** [comment]
Ei ajeta. Toistaiseksi skreipperit otetaan mukaan koodikatselmoinnin kautta ja ne ajetaan datavaalit-käyttäjän oikeuksilla virtuaalipalvelimellamme.
