### ISSUE TITLE
Vaalirahoituksen lisääminen kantaan

### ISSUE THREAD

**Issue by juyrjola** [kansanmuisti/datavaalit#14]
Datat löytyy täältä:

http://www.vaalirahoitusvalvonta.fi/fi/index/vaalirahailmoituksia/raportit/Tietoaineistot.html.stx

Ensin pallo Joonalle tietomallin päivitystä varten.

**Comment by juyrjola** [comment]
Aineistossa on viitattu ehdokkaaseen kaikilla etunimillä. Meillä on toistaiseksi kannassa ainoastaan kutsumanimi. Oikea ehdokas voidaan varmaan kuitenkin löytää, koska tiedetään lisäksi puolue ja kunta.

**Comment by apoikola** [comment]
http://www.puoluerahoitus.fi/fi/index/vaalirahailmoituksia/raportit/Tietoaineistot.html.stx tämän sisältö päivittyy jatkuvasti, nyt olisi hyvä aika alkaa tallentamaan versioita automaattisesti, että saisi esim. käyrää siitä, missä tahdissa ehdokkaat submittaavat vaalirahoitusilmoituksiaan

**Comment by jlehtoma** [comment]
Ajatuksena oli, että aineisto päivittyisi esim. kerran viikossa. Kun asiaa miettii tarkemmin, niin päivittäinen päivittäminen olisi varmaan paikallaan.

**Comment by jlehtoma** [comment]
@juyrjola onko kokemuksia django-cron:ista http://code.google.com/p/django-cron/ ? Vai mikä olisi hyvä tapaa ajaa hakuja ja käsittelyjä automaattisesti? Vai onko hyvä idea ollenkaan?

**Comment by juyrjola** [comment]
@jlehtoma, en oo käyttänyt. Commit-login perusteella projekti on aika kuollut, mutta vähän viriilimpi versio näyttäisi olevan täällä: https://github.com/Tivix/django-cron

Kyllä me jotain ton tyylistä ehdottomasti tarvitaan. Vähän työläämpien prosessointien tekemiseen on trendikästä käyttää async workereita, esim. http://joshbohde.com/blog/async-workers-in-django-with-celery . En tosin tiedä, miten noi taipuisivat meidän käyttötapauksiimme.

**Comment by juyrjola** [comment]
Tjaa, Celery voisi taipuakin: http://docs.celeryproject.org/en/master/userguide/periodic-tasks.html

**Comment by jlehtoma** [comment]
Toihan näyttää aika lupaavalta, palataan asiaan kunhan saan hommia vähän eteenpäin

**Comment by apoikola** [comment]
http://datavaalit.muistio.tieke.fi/hakserointisunnuntai rivi 14:

Ville
Vaalirahoitusilmoitukset päätyvät nyt 4x vuorokaudessa => http://tmp.ypcs.fi/data/kunnallisvaalit2012/ (lähde: http://www.puoluerahoitus.fi/fi/index/vaalirahailmoituksia/raportit/Tietoaineistot.html.stx)

**Comment by jlehtoma** [comment]
@juyrjola olisko helpoin tapa populoida nuo vaalirahailmoitustaulut kirjoittaa se importteri? Onko niin, että valtaosalle kantaan tuupattavasti datasta importtaus tapahtuu nyt stats.management.commands.stat:in kautta ? Eli:

1) Entry pointiksi run-importers.py 
2) Uus tyyppi DATA_TYPES tupleen
3) (vähän pitää vielä selvitellä tota importteri-logiikkaa)
4) toteutus submit_expenses (tms)

**Comment by juyrjola** [comment]
Se management-komento on legacy-tapa, koska se ei ole kauhean joustava eikä portattava. En ole vielä siirtänyt sinne jääneitä importtereita uuteen tyyliin.

Uuden tietotyypin tekeminen menee jotakuinkin noin. submit_*-funkkarit kannattaa kirjoittaa sekä dummy-backendiin (importers/base.py) että django-backendiin. Importteria koodatessa pitää vielä:
- kirjoittaa importterikoodi =) (esim. importers/fi/vaalirahoitus.py)
- lisätä importteri listaan importers/list.py (esim. "import importers.fi.vaalirahoitus")

**Comment by jlehtoma** [comment]
llmoituksissa on mukana sekä 1) kustannukset (kulut) että 2) rahoitus. Molemmille on omat  erittelynsä. Väsäsin tietomallia molemmille, tältä näyttää:

http://dl.dropbox.com/u/599386/db_plans.png

Jossei haluta kaikkea kerralla mukaan, niin kulut nyt ainakin ensin. Malli on hiukan redundantti, sillä sekä kulujen (CandidateExpenses) että rahoituksen (CandidateFundind) kentät ovat samat. Mikähän olisi paras tapa hanskata tämä? 
1. Erilliset taulut sekä transaktioille (Expense/Funding) että tyypeille (ExpenseType/FundType) (kuten nyt kuvassa)
2. Transaktiot yhdessä taulussa, tyypit toisessa. Erottelu summakentän (sum) merkin (+/-) kautta
3. Transaktiot yhdessä taulussa, tyypit toisessa. Erottelu erillisen tyyppikentän ("E"/"F") kautta tyyppitaulussa

Jatkan nyt tuon vaihtoehdon 1 pohjalta kun olen jo aloittanut.

Aikaleima voisi olla hyödllinen taulussa jos haluaa seurata ilmoitusten kertymistä.

**Comment by jlehtoma** [comment]
Nyt olis perustoiminnallisuus noiden ennakkoilmojen kulujen osalta kasassa:

https://github.com/jlehtoma/datavaalit/commit/97024f36d5f205545e5e03c6e9cac9442f1b3eee

Eli mukana on nyt vaan dummy-backend, seuraavaks toi Django-backend

**Comment by juyrjola** [comment]
Hienoa, hyvältä näyttää! Lisäsin muutamia kommentteja muutoksiin.

**Comment by juyrjola** [comment]
Niin ja vaihtoehto 1 on ihan jees. Mä en ainakaan keksinyt tältä istumalta abstraktia nimeä, joka kuvaisi sekä tuloja että menoja...

**Comment by jlehtoma** [comment]
Django-backend toimii nyt jotenkuten, löytyy täältä:

https://github.com/jlehtoma/datavaalit/commit/81712822cb17099ea0971c757f348a9a21aff71e

Ennakkoilmoituksia on toistaiseksi jättänyt 882 ehdokasta. 306 ei pysty yhdistämään Person-tauluun etunimi+sukunimi+kunta -kombolla. Tuolla siis ilmoitettuna useita etunimiä,  yksinkertainen heurustiikka käy läpi muutkin etunimet jos ekalla ei natsaa. Joka tapauksessa puuttuvia henkilöitä on niin paljon, että tämä pitäisi katsoa läpi. Käytin referenssinä Candidates-taulua, jonka importtasin tänään, N=37869.

**Comment by jlehtoma** [comment]
Automaattinen tietojen nouto (kerran tunnissa?) pitäisi kanssa toteuttaa vielä. Tällä hetkellä Django-backend ei myöskään päivitä olemassa olevia tietuita, vaan ainoastaan lisää uudet.

**Comment by jlehtoma** [comment]
Ja vielä: run_importers.py:ssä  on uusi vipu --disable-cache. Lisäsin loggerin ouputtiin lisäksi levelnamen tulosteen selkeyttämiseksi.

**Comment by jlehtoma** [comment]
Hajotin Issuen kolmeksi tarkemmaksi tehtäväksi ([#19](https://github.com/kansanmuisti/datavaalit/issues/19), [#20](https://github.com/kansanmuisti/datavaalit/issues/20) ja [#21](https://github.com/kansanmuisti/datavaalit/issues/21) ) ja suljen tämän.
