### ISSUE TITLE
Datavaalit.fi/resources alasivujen linkittäminen

### ISSUE THREAD

**Issue by apoikola** [kansanmuisti/datavaalit#26]
Nämä pitäisi saada käyttiksessä alasivuiksi

http://www.datavaalit.fi/resources/api/

http://www.datavaalit.fi/resources/clean-data/

http://www.datavaalit.fi/resources/catalogue/

**Comment by jlehtoma** [comment]
@apoikola : tarkoitat siis yläpalkin valikon 'Resurssit' alavalikoiksi?

**Comment by apoikola** [comment]
jep
