### ISSUE TITLE
urjala, näyttää tiedot väärin rahoituksista

### ISSUE THREAD

**Issue by JaspaJami** [kansanmuisti/datavaalit#37]
Jostain syystä Urjalan kohdalla näkyy että ennakkoilmoituksia olisi Vihreiden kohdalta 80% ja keskustan kohdalta 6.3%. Totuus on kuitenkin se että keskusta ei ole tehnyt yhtään ilmoitust ja Vihreistä on tällä hetkellä tehnyt kaikki.

Todennäköisin syy on se että nimissä käytetään vain etunimi/sukunimi määritystä ja Uralassa on ehdolla kaksi Mauri Järvistä, toinen keskusta ja toinen vihreä (minä). Olen myös ensimmäinen Urjalassa ilmoituksen tehnyt joten ja datavaalien mukaan ekan ilmoituksen on tehnyt keskustalainen.

Eli jostain syystä minusta on nyt tullut keskustalainen teidän sivuilla :)

t. Mauri "Jami" Järvinen.

**Comment by jlehtoma** [comment]
Terve Mauri!

Katselin vähän tuota meidän kantaa ja olet oikeassa, sekaannus johtuu siitä, että Urjalassa on kaksi Mauri Järvistä. Ehdokastietojen ja vaalirahoitusilmoitusten täsmääminen on ollut osin vaikeaa kirjavien nimikäytäntöjen takia ja me ollaan tosiaan käytetty etunimi/sukunimi/kunta - määritystä ja edelleen epäselvissä tapauksissa ratkaistu tilanne manuaalisesti. Systeemimme ei edes tajunnut herjata teidän tapauksessa mitään, koska ehdokastiedoissa etunimesi on "Mauri (Jami)". Haku löysi sen sijaan keskustalaisen Mauri Järviseen.

Puoluetiedon heittäminen mukaan soppaan voisi tarjota vielä vähän lisää tarkkuutta, mutta korjataan tämä sinun tietosi nyt ensin manuaalisesti.

**Comment by juyrjola** [comment]
Kiitti raportoinnista, korjattu!

**Comment by JaspaJami** [comment]
Hieno homma. Kiitos nopeasta toiminnasta. Itse rummuttanut tästä jonkun verran somessa niin olihan se noloa kun ei kuitenkaan itseni kohdalla näkynyt tiedot oikein täällä :)

**Comment by apoikola** [comment]
Toivottavasti pysyy korjattuna, ettei virhe toistu dataa päivitettäessä... nimimerkki vainoharhainen

**Comment by jlehtoma** [comment]
Ei pitäisi toistua, henkilön täsmääminen tässä tapauksessa on nyt varmistettu oikeaksi. Kannattaa tietenkin pysyä valppaana, kaiken varalta.
