### ISSUE TITLE
Henkilötietojen muutos-/poistonapit

### ISSUE THREAD

**Issue by jlehtoma** [kansanmuisti/datavaalit#4]

**Comment by apoikola** [comment]
Jos tämä koskeen sosiaalisen median fiidejä, niin ehdokkailta tuntuu tulevan myös fiidien lisäyspyyntöjä, joten tämä nappi pitäisi olla... voi olla yksinkertaisimmillaan linkki Google formiin, jolla tiedot kerätään ja sitten voi manuaalisesti tehdä poistoja/lisäyksiä

**Comment by juyrjola** [comment]
Pyyntökaavake on nyt täällä:

http://www.datavaalit.fi/candidates/change-request/

Jotkut ehdokkaat ovatkin jo löytäneet sen ja lähettäneet fiidien lisäyspyyntöjä.
