### ISSUE TITLE
Henkilörekisterikysymysten selvittäminen EU-tietosuojavaltuutetulta

### ISSUE THREAD

**Issue by jlehtoma** [kansanmuisti/datavaalit#5]

**Comment by apoikola** [comment]
Aloitin asian hoitamista kysymällä Ville Oksaselta: http://www.facebook.com/tietopyynto/posts/234471246649742

**Comment by juyrjola** [comment]
Mun kontakti on Zsuzsanna (http://okfestival.org/personal-data/). Hän sohvasurffasi mun luona festin aikana ja oli oikein kiinnostunut meidän demokratia- ja avoimen data proggiksista. Onko meillä jotain englanninkielistä kuvausta Datavaaleista jo valmiina?

**Comment by antagomir** [comment]
Engine Roomin kaverit myöskin kyseli englanninkielistä tiedotetta. OKFestin sivulta löytyy suomen- ja englanninkieliset tiedotteet. Englanniksi on sivun alussa lyhyempi kuvaus, ja lopussa vähän pidempi: http://okfestival.org/datavaalit-data-elections-launch/

**Comment by juyrjola** [comment]
Lähetin Zsuzsannalle meilin, katsotaan mitä sieltä vastataan.

**Comment by juyrjola** [comment]
Niin joo, Zsuzsannalta tuli nopea vastaus, jonka ydin on tässä: "[...] as far as I know European laws are unfortunately not very clear on these and related issues. There is also a huge variation between what is judged permissible in one country compared to another. Finland, in general, is much more open [...]"

Eli Suomen lakien mukaan mennään.
