### ISSUE TITLE
Datan lisäämisen joukkoistamis-workflow

### ISSUE THREAD

**Issue by jlehtoma** [kansanmuisti/datavaalit#6]

**Comment by apoikola** [comment]
Konkreettinen askel tähän suuntaan olisi meidän kommunikaatiovälineiden ja kanavien listaaminen sivulla. Olen visioinut päässäni mallia, jossa olisi visuaalinen ikoni ja lyhyt selitys + linkki vierekkäin tyyliin:

[Githubin logo]  - Datavaalit sivuston tekninen dokumentaatio (wiki), lähdekoodi (repo) ja kehitys (issue tracker).

Kaikki kanavathan ovat listattuna täällä: http://datavaalit.muistio.tieke.fi/sivusto

**Comment by juyrjola** [comment]
Antti, jos haluat protoilla ideaasi käytännössä, meidän CMS:n kautta pitäisi onnistua hienosti vanhojen sivujen muokkaus ja uusien lisääminen. Tarkoitus olisi tehdä staattiset sivut wikiksi, mutta Django-pohjainen uusi superwiki (https://github.com/benjaoming/django-wiki) on tällä hetkellä kovan kehityksen alla ja ajattelin ottaa sen käyttöön vasta koodikannan stabilisoiduttua. Sen pitäisi tapahtua lokakuussa.

Voidaan käydä vaikka skypen välityksellä läpi miten prosessi toimii tällä hetkellä. Joona, suakin saattaisi kiinnostaa.

**Comment by jlehtoma** [comment]
Antti: jotain samantyyppistä olin itsekin hahmotellut päässäni. Nimensä mukaisesti "workflowta" voisi visualisoida nimenomaan sarjana tapahtumia ja ikoneita, eli "selaa mahdollisia datoja" -> "raavi dataa" -> "siivoa dataa" -> "tuuppaa data Datavaalien tietokantaan" tms. Siis tämä vain yksi esimerkki.

Juha: Ilman muuta kiinnostaa ja voin myös osallistua Sype-paltsuun.

**Comment by apoikola** [comment]
Tyhmiä kysymyksiä by Jogi:

1# olinkos mä kai ehkä rekisteröitynyt myös Datavaalit.fi ylläpitäjäksi? Millä tunnuksilla mistä pääsen sisään?
2# mitä kaikkea on kannassa jo? mistä sen tietää / näkee

**Comment by juyrjola** [comment]
@apoikola, oot aikoinaan tehnyt itsellesi tunnarin ja sut on lisätty ylläpitäjäksi. Sisään pääsee kirjautumaan täältä: http://www.datavaalit.fi/account/login/ . Siihen ei ole mitään linkkiä sivustolta, koska käyttäjätunnuksilla ei muut kuin ylläpitäjät tee (vielä) mitään. Oikeasta yläkulman tunnarivalikosta pääsee ylläpitokäyttöliittymään.

CMS / Sivut -osiossa voi muokata sivuston staattista sisältöä. Käyttöliittymä ei ehkä ole kaikista intuitiivisin, mutta täältä löytyy vähän vinkkejä: http://docs.django-cms.org/en/2.2/getting_started/tutorial.html#creating-your-first-cms-page

**Comment by apoikola** [comment]
@juyrjola thx ... kokeilin summana tätä http://www.datavaalit.fi/admin/ joka johti muualle, nyt pääsen sisään... ensivaikutelma grafiikan perusteella on Joomlamainen uff :/ mutta opiskelen nyt
